### ISSUE TITLE
Documentation error.

### ISSUE THREAD

**Issue by e0ipso** [Gizra/entity_validator#16]
I noticed this when reading your post in Gizra's blog.

https://github.com/Gizra/entity_validator/blob/7.x-1.x/modules/entity_validator_example/plugins/validator/node/article/EntityValidatorExampleArticleValidator.class.php#L11

``` php
/**
 * Overrides EntityValidateBase::setFieldsInfo().
 */
```

**Comment by RoySegall** [comment]
@mateu-aguilo-bosch Thanks for the notice. There might be an API change in of the follow up PR.
