### ISSUE TITLE
Can't translate errors 

### ISSUE THREAD

**Issue by RoySegall** [Gizra/entity_validator#28]
It seems that we can't translate errors. I think we forgot to wrap the text with `t()`

**Comment by RoySegall** [comment]
@amitaibu @mateu-aguilo-bosch I think this might relate to Restful. My current language set to hebrew and i want to translate the errors that i set in the entity validator handler. I think we need to pass the language code in the GET/POST request and set the language. Does a language negotiation is required here is this a an overkill for that?

**Comment by e0ipso** [comment]
@RoySegall I don't think error exception messages are translated often. If you need to surface the exception message to the user (you only want translation for the users) then you can catch the exception and wrap it with a `t()`.
