### ISSUE TITLE
Release 7.x-2.x to Drupal.org

### ISSUE THREAD

**Issue by e0ipso** [Gizra/entity_validator#42]
Is `7.x-2.x` ready to release in drupal.org?

**Comment by e0ipso** [comment]
Unless we push `7.x-2.x` to drupal.org and create a new dev release for the `Entity Validator`, https://github.com/RESTful-Drupal/restful/pull/668 will be blocked.

**Comment by RoySegall** [comment]
I added the release. Let's wait for d.o to built to compile the release.

**Comment by e0ipso** [comment]
Thank you!

**Comment by RoySegall** [comment]
@e0ipso I think we can close this issue:
![entity_validator___drupal_org](https://cloud.githubusercontent.com/assets/1222368/10601517/08720c96-771b-11e5-8f77-37ed2c984f67.png)

**Comment by e0ipso** [comment]
Indeed!

Thanks again.
