### ISSUE TITLE
Incorrect validator for title field in example module (1.x)

### ISSUE THREAD

**Issue by secmon** [Gizra/entity_validator#50]
Example module's class (EntityValidatorExampleArticleValidator in file modules\entity_validator_example\plugins\validator\node\article\EntityValidatorExampleArticleValidator.class.php) contains incorrect validator for _title_ field:
`$public_fields['title']['validators'][] = array($this, 'validateBodyText');`

Should be
`$public_fields['title']['validators'][] = array($this, 'validateTitleText');`

**Comment by RoySegall** [comment]
10x. Any chance for a PR?

**Comment by secmon** [comment]
Sorry. My fault. It's fixed in 1.x branch... But not in v1.1 (from drupal.org)
